#!/bin/tcsh
# ===========================================================================
# 
# mkasm64 --
# 
# 
# Ralf Moeller <moeller (see www.techfak.uni-bielefeld.de/ags/ti)>
# 
#    Copyright (C) 2004
#    Computer Engineering Group
#    Faculty of Technology
#    University of Bielefeld
# 
# 1.0 / 11. May 04 (rm)
# - from scratch
# 1.1 / 19. Mar 09 (rm)
# - -g option: gdb shows the line
# 
# ===========================================================================

# -m elf_x86_64 is also used by gcc (use gcc -v to show all steps)

if ($# != 1) then
	echo "usage: mkasm <binary_name>"
	echo "  nasm -g -f elf64 <binary_name>.asm"
	echo "  ld -m elf_x86_64 -static -o <binary_name> <binary_name>.o"
	exit -1
endif

# we remove ending (just to be sure)
set binary_name=$1:r
nasm -g -f elf64 -F dwarf ${binary_name}.asm
ld -m elf_x86_64 -static -o ${binary_name} ${binary_name}.o